language: r
cache: packages
warnings_are_errors: true
use_bioc: true
bioc_required: true
cran: http://cran.rstudio.com
dist: trusty
addons:
  apt:
    packages:
    - libfftw3-dev
    - libgsl0-dev
    - libgsl0ldbl
    - jags
os:
- linux
- osx
osx_image: xcode9.4
services:
- xvfb
r:
- 3.3
- 3.4
- 3.5
- release
- devel
matrix:
  allow_failures:
  - r: devel
env:
  global:
  - RGL_USE_NULL=TRUE
  - PROJECT_NAME=oslerinhealth-releases
  - DISPLAY=:99.0
r_check_args: "--as-cran --install-args=--build"
before_install:
- ulimit -n 2048
- export PROJ_DIR=`basename $PWD`
- fname=travis_helpers.sh
- wget -O ${fname} http://bit.ly/travis_helpers
- cat ${fname}; source ${fname}; rm ${fname}
- cat DESCRIPTION
- codename=`linux_codename`;
- if [ "${codename}" = "trusty" ]; then start_xvfb ; fi
- export rver=`r_version`; echo $rver ;
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then no_open_mp ; fi
- jags_install || true;
- v8_install || true;
- dcmtk_install || true;
- gsl_install 2.1 || true ;
- remove_neuroc_packages
- cat DESCRIPTION
- install_remotes_no_dep
- cat DESCRIPTION
- export PACKAGE_NAME=`package_name`
- echo "Package Name is $PACKAGE_NAME"
- install_python_requirements ;
after_success:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
after_failure:
- cat ${PACKAGE_NAME}.Rcheck/00install.out
- cat ${PACKAGE_NAME}.Rcheck/00check.log
before_deploy:
- if [ "$TRAVIS_OS_NAME" = "osx" ]; then PKG_TARBALL=$(ls -1t *.tgz | head -n 1);
  PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tgz/_'"R${rver}"'.tgz/'` ; mv ${PKG_TARBALL}
  ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}" ; fi
- if [ "$TRAVIS_OS_NAME" = "linux" ]; then PKG_TARBALL=$(ls -1t *.tar.gz | head -n
  1); PKG_TARBALL_WITH_R=`echo $PKG_TARBALL | sed 's/.tar.gz/_'"R${rver}"'.tar.gz/'`
  ; mv ${PKG_TARBALL} ${PKG_TARBALL_WITH_R} ; echo "Built tarball is ${PKG_TARBALL_WITH_R}"
  ; fi
- if [[ "${TRAVIS_OS_NAME}" = "osx" ]]; then rm -f *.tar.gz; fi
deploy:
  provider: releases
  skip_cleanup: true
  file_glob: true
  file: "${PACKAGE_NAME}*.t*gz"
  on:
    tags: true
  api-key:
    secure: oVimeagUjY0DoEh0zx87DFHnoVBTFo6diy4PXJAVycLz98UxjhjkTdzjxMT2aiKpZ825Fvc3vPrhU0q1iD/lyUvlCMs21AiubhjKwcN+77VpKRWrv6hfotNeW2QPjcqDKnkx4s0Y9yFmiozreHHp+hQ2LvlmhqLcSJchCVq8JP09V/PMMTtkESqodJeSf5NVC69xV/RgT9eaEqorwT2/m4Z+awaYO28BoJnYpywno7GmvJnXEWrg3xHYk+XuJdefcKjIdOfCqIkgMPRzlyDcpehrn7CiD3KLEYYGZnTVqKqpro87Vd+fgu3zV/550oHqdnKTS2EVvNt9BuhTsp4y6mz8mjCev5pu9s4ToCw/22owg10yaPJvdOd1NNFaQP/hbhjyECsJRYToBt+40GYBIiPhLRy6v/1NwacGkATathcKdBHCGTxwTyCcuKtsXc9kqV+4rvOvCbnipCrBot0RuMaELkJ3alwmXRkEr9BGhVed7zA01ZdKU8Kp9TfoVDoIlzbdbb58tZ8/O/+sjlRkyHFn1WZ9YRljQzOw17g0KsUYHG7rxv/hJZA7B98OeYylS8nYcSjITho/FWaJfXpJhjYPhszR4uQTUT2NIuKd+zcdeiPo4mSFx22/8RGAnxLxFMHeM11ms1xBVzwO9JVfFFLWP+5/9IiXbVMJ8Ds7z94=
after_deploy:
- echo "${PROJECT_NAME}" | grep -q "releases"; if [[ $? -eq 0 ]]; then run_coverage="false";
  else run_coverage=; fi;
- if [[ "${TRAVIS_OS_NAME}" == "linux" && ${TRAVIS_R_VERSION_STRING} = "release" &&
  -z "${run_coverage}" ]]; then echo 'covr::coveralls(type = "all", quiet = FALSE)'
  > osler_covr.R ; travis_wait 100 Rscript osler_covr.R ; rm osler_covr.R ; fi

#neuroc.deps version (SHA): a5aa5ca